version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db-manager"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root@123##"

  web:
    build: .
    command: gunicorn db_manager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: