# Generated by Django 5.0.6 on 2024-08-25 08:59

import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, default=None, max_length=79, null=True)),
                ('host', encrypted_model_fields.fields.EncryptedCharField(help_text='Example: localhost')),
                ('name', encrypted_model_fields.fields.EncryptedCharField(help_text='Specify your database name')),
                ('user', encrypted_model_fields.fields.EncryptedCharField(help_text='Example: root')),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('port', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
