# Generated by Django 5.0.6 on 2024-08-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
