# Generated by Django 5.0.6 on 2024-08-26 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0002_database_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='database',
            name='database_type',
            field=models.CharField(choices=[('mysql', 'My SQL'), ('postgres', 'Postgres')], default='mysql', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='database',
            name='id',
            field=models.TextField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
