# Author: Manpreet Singh
# Email: dev.manpreet.io@gmail.com
# GitHub: https://github.com/craft-with-manpreet
# Portfolio: https://dev-manpreet.web.app
# Generated by Django 5.0.6 on 2024-08-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('database_management', '0005_databaselog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaselog',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='database',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='databaselog',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_logs',
                                    to='database_management.database'),
        ),
    ]
