# Author: Manpreet Singh
# Email: dev.manpreet.io@gmail.com
# GitHub: https://github.com/craft-with-manpreet
# Portfolio: https://dev-manpreet.web.app
# Generated by Django 5.0.6 on 2024-08-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('database_management', '0006_alter_databaselog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granularity', models.CharField(
                    choices=[('hourly', 'hourly'), ('everyday', 'Everyday'), ('weekly', 'Weekly'),
                             ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedule',
                                   to='database_management.database')),
            ],
        ),
    ]
