# Generated by Django 5.0.6 on 2024-08-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0008_alter_backupschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupschedule',
            name='database',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedule', to='database_management.database'),
        ),
    ]
